version: '3.1'

services:
  my-mongodb:
    image: mongo:latest
    container_name: my-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=noelia
      - MONGO_INITDB_ROOT_PASSWORD=changeme
    ports:
      - 27017:27017
